---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Shanghai"
    target-branch: "release"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"

  - package-ecosystem: "docker"
    directory: "/v0"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Shanghai"
    target-branch: "release"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"

  - package-ecosystem: "docker"
    directory: "/v1"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Shanghai"
    target-branch: "release"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
