---
name: "Build v0"

on:
  push:
    branches: [master]
    paths:
      - "v0/**"
      - "!v0/**.md"
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKERHUB_REPO: ${{ secrets.DOCKER_USERNAME || github.repository_owner }}/nezha-dashboard
  IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
  TZ: Asia/Shanghai
  WORK_DIR: v0

jobs:
  check:
    name: "Pre check"
    runs-on: ubuntu-latest
    outputs:
      renew: ${{ steps.vers.outputs.renew }}

    steps:
      - name: "Fetch Versions and Decide"
        id: vers
        run: |
          set -eEuxo pipefail
          RENEW="false"
          CURRENT_DAY="$(date -u '+%d')"
          if [[ "$CURRENT_DAY" == "01" ]]; then
            echo "Build required."
            RENEW="true"
          fi
          echo "renew=$RENEW" >> "$GITHUB_OUTPUT"

  release:
    name: "Build binary"
    runs-on: ubuntu-latest
    needs: [check]
    if: needs.check.outputs.renew == 'true' || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: true
      matrix:
        nezha_tag: ["v0.18.6", "v0.20.13"]
    permissions:
      contents: write

    steps:
      - name: "checkout repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Remove existing tag"
        run: |
          set -eEuxo pipefail
          if git tag --list | grep -q "^${{ matrix.nezha_tag }}$"; then
            git push origin --delete ${{ matrix.nezha_tag }}
          fi

      - name: "checkout nezha src"
        uses: actions/checkout@v6
        with:
          repository: nezhahq/nezha
          ref: ${{ matrix.nezha_tag }}
          path: ${{ env.WORK_DIR }}/src

      - name: "Prepare assets"
        working-directory: ${{ env.WORK_DIR }}/src
        run: |
          set -eEuxo pipefail
          cp $GITHUB_WORKSPACE/scripts/replace.sh .
          bash replace.sh
          rm -f pkg/geoip/geoip.db || exit 1
          rm -f replace.sh || exit 1
          curl -Ls -k "https://ipinfo.io/data/free/country.mmdb?token=$IPINFO_TOKEN" -o pkg/geoip/geoip.db

      - name: "Extract version"
        id: vers
        run: |
          set -eEuxo pipefail
          echo "nezha_version=$(sed 's/^v//' <<< ${{ matrix.nezha_tag }})" >> "$GITHUB_OUTPUT"

      - name: "Build binaries"
        uses: crazy-max/ghaction-xgo@v3
        with:
          xgo_version: latest
          go_version: 1.23.x
          dest: dist
          pkg: cmd/dashboard
          prefix: dashboard
          targets: linux/amd64,linux/arm64
          v: true
          x: false
          race: false
          tags: timetzdata
          ldflags: -s -w --extldflags '-static -fpic' -X github.com/naiba/nezha/service/singleton.Version=${{ steps.vers.outputs.nezha_version }}
          buildmode: default
          trimpath: true
          working_dir: ${{ env.WORK_DIR }}/src

      - name: "Package assets"
        working-directory: ${{ env.WORK_DIR }}/src
        run: |
          set -eEuxo pipefail
          pushd dist || exit 1
          touch -mt "$(date +%Y01010000)" -- *
          for f in *; do
            if [ -f "$f" ]; then
              PLATFORM=${f#dashboard-}
              PACKAGE_NAME="dashboard-${{ steps.vers.outputs.nezha_version }}-${PLATFORM}"
              mkdir "$PACKAGE_NAME"
              cp "$f" "$PACKAGE_NAME/dashboard"
              sha256sum "$PACKAGE_NAME/dashboard" | sed 's| .*| dashboard|' > "$PACKAGE_NAME/checksum.txt"
              cp $GITHUB_WORKSPACE/LICENSE "$PACKAGE_NAME"
              cp $GITHUB_WORKSPACE/README.md "$PACKAGE_NAME"
              tar cfvz "$PACKAGE_NAME.tar.gz" "$PACKAGE_NAME"
              rm -rf "$PACKAGE_NAME" || exit 1
            fi
          done
          popd || exit 1

      - name: "Upload Release"
        uses: softprops/action-gh-release@v2
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          files: ${{ env.WORK_DIR }}/src/dist/*.tar.gz
          tag_name: ${{ matrix.nezha_tag }}
          fail_on_unmatched_files: true
          generate_release_notes: true

  build:
    name: "Build image"
    needs: [check]
    if: needs.check.outputs.renew == 'true' || github.event_name == 'workflow_dispatch'
    strategy:
      fail-fast: true
      matrix:
        nezha_tag: ["v0.18.6", "v0.20.13"]
        arch: [amd64, arm64]
        include:
          - { arch: amd64, os: ubuntu-24.04, platform: linux/amd64 }
          - { arch: arm64, os: ubuntu-24.04-arm, platform: linux/arm64 }
    runs-on: ${{ matrix.os }}

    steps:
      - name: "Prepare"
        run: |
          PLATFORM_PAIR="$(awk -F/ '{print $1"-"$2$3}' <<< ${{ matrix.platform }})"
          echo "PLATFORM_PAIR=$PLATFORM_PAIR" >> "$GITHUB_ENV"

      - name: "Checkout repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Stage build assets"
        working-directory: ${{ env.WORK_DIR }}
        run: |
          set -eEuxo pipefail
          cp $GITHUB_WORKSPACE/scripts/docker-entrypoint.sh .
          cp $GITHUB_WORKSPACE/scripts/replace.sh .

      - name: "Fetch geoip db"
        working-directory: ${{ env.WORK_DIR }}
        run: |
          set -eEuxo pipefail
          curl -Ls -k "https://ipinfo.io/data/free/country.mmdb?token=$IPINFO_TOKEN" -o geoip.db

      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to DockerHub"
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Docker metadata"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          tags: type=raw,value=${{ matrix.nezha_tag }}
          labels: |
            org.opencontainers.image.description=Nezha monitoring is self-hosted, lightweight server and website monitoring and O&M tool
            org.opencontainers.image.source=https://github.com/nezhahq/nezha
            org.opencontainers.image.title=Nezha
            org.opencontainers.image.url=https://nezha.wiki

      - name: "Build and export"
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.WORK_DIR }}
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: NEZHA_VERSION=${{ matrix.nezha_tag }}
          outputs: type=image,name=${{ env.DOCKERHUB_REPO }},push-by-digest=true,name-canonical=true,push=true

      - name: "Export digest"
        run: |
          rm -rf /tmp/digests
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: "Upload artifact"
        uses: actions/upload-artifact@v6
        with:
          name: digest-${{ matrix.nezha_tag }}-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    name: "Merge manifest"
    runs-on: ubuntu-latest
    needs: [check, build]
    strategy:
      fail-fast: true
      matrix:
        nezha_tag: ["v0.18.6", "v0.20.13"]

    steps:
      - name: "Download digests"
        uses: actions/download-artifact@v7
        with:
          path: /tmp/digests
          pattern: digest-${{ matrix.nezha_tag }}-*
          merge-multiple: true

      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to DockerHub"
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Docker metadata"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          tags: type=raw,value=${{ matrix.nezha_tag }}
          labels: |
            org.opencontainers.image.description=Nezha monitoring is self-hosted, lightweight server and website monitoring and O&M tool
            org.opencontainers.image.source=https://github.com/nezhahq/nezha
            org.opencontainers.image.title=Nezha
            org.opencontainers.image.url=https://nezha.wiki

      - name: "Create manifest list and push"
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create \
            $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.DOCKERHUB_REPO }}@sha256:%s ' *)

      - name: "Inspect image"
        run: |
          docker buildx imagetools inspect ${{ env.DOCKERHUB_REPO }}:${{ matrix.nezha_tag }}
