---
name: "GitHub Actions Mirror"

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  mirror_to_framagit:
    name: "Mirror to framagit"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Mirror to framagit"
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: git@framagit.org:${{ github.repository }}.git
          GIT_SSH_PRIVATE_KEY: ${{ secrets.SYNC_PRIVATE_KEY }}
          GIT_SSH_NO_VERIFY_HOST: true
          PUSH_ALL_REFS: false
          GIT_PUSH_ARGS: "--force --prune"

  mirror_to_codeberg:
    name: "Mirror to codeberg"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Mirror to codeberg"
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: git@codeberg.org:${{ github.repository }}.git
          GIT_SSH_PRIVATE_KEY: ${{ secrets.SYNC_PRIVATE_KEY }}
          GIT_SSH_NO_VERIFY_HOST: true
          PUSH_ALL_REFS: false
          GIT_PUSH_ARGS: "--force --prune"
